export const PROJECTS = [
  {
    name: "ColorWaste",
    url: "https://colorwaste.com",
    tag: "C++ / JS / PHP / MySQL ",
    subject: "Machine Learning",
    branch: "Computer Vision",
    date: "February 2026",
    status: "Completed",
    shortDesc:
      "ColorWaste is a waste segregation system using computer vision and sensors to automatically classify waste. It provides real-time feedback through a dashboard",
    icon: "/ColorWaste.png",
    image: null,
    video: "/Dashboard - Demo Vid.mp4",
    videoLabel: "Dashboard Demo",
    video2: "/Prototype - Demo Vid.mp4",
    video2Label: "Prototype Demo",
    iconLabel: "ColorWaste Website",
    logo: "/ColorWaste.png",
  },
  {
    name: "Portfolio",
    url: null,
    tag: "React / Three.js",
    subject: "Web Development",
    branch: "Front-End",
    date: "March 2026",
    status: "In-Progress",
    shortDesc:
      "Emmanuel Dionne B. Catibog's personal portfolio, showcasing his skills, projects, and experience as a Computer Science student.",
    icon: null,
    image: null,
    video: null,
    logo: null,
  },
  {
    name: "Album",
    url: null,
    tag: "Node / WS",
    subject: "Web Development",
    branch: "Front-End",
    date: "February 2026",
    status: "Completed",
    shortDesc:
      "Album website I made to view personal images and personalized letters.",
    icon: null,
    image: null,
    video: null,
    logo: null,
  },
  {
    name: "Img to ASCII",
    url: null,
    tag: "React / Canvas API",
    subject: "Image Processing",
    branch: "Creative Coding",
    date: "April 2026",
    status: "Work in Progress",
    shortDesc:
      "A drawing application built with React and Canvas API that converts drawings and uploaded images into ASCII art. Features adjustable brush, eraser tool, image upload, and real-time canvas manipulation.",
    icon: null,
    image: null,
    video: null,
    logo: null,
  },
];
