export const PROJECTS = [
  {
    name: "ColorWaste",
    url: "https://colorwaste.com",
    tag: "C++ / JS / PHP / MySQL ",
    subject: "Machine Learning",
    branch: "Computer Vision",
    date: "February 2026",
    status: "Completed",
    shortDesc:
      "ColorWaste is a waste segregation system using computer vision and sensors to automatically classify waste. It provides real-time feedback through a dashboard",
    icon: "/ColorWaste.png",
    image: null,
    video: "/Dashboard - Demo Vid.mp4",
    videoLabel: "Dashboard Demo",
    video2: "/Prototype - Demo Vid.mp4",
    video2Label: "Prototype Demo",
    iconLabel: "ColorWaste Website",
    logo: "/ColorWaste.png",
  },
  {
    name: "Portfolio",
    url: null,
    tag: "React / Three.js",
    subject: "Web Development",
    branch: "Front-End",
    date: "March 2026",
    status: "In-Progress",
    shortDesc:
      "Emmanuel Dionne B. Catibog's personal portfolio, showcasing his skills, projects, and experience as a Computer Science student.",
    icon: null,
    image: null,
    video: null,
    logo: null,
  },
  {
    name: "Album",
    url: null,
    tag: "Node / WS",
    subject: "Web Development",
    branch: "Front-End",
    date: "February 2026",
    status: "Completed",
    shortDesc:
      "Album website I made to view personal images and personalized letters.",
    icon: null,
    image: null,
    video: null,
    logo: null,
  },
  {
    name: "Data Dashboard",
    url: null,
    tag: "D3 / React",
    subject: "Data Visualization",
    branch: "Analytics",
    date: "—",
    status: "—",
    shortDesc: "Placeholder description.",
    desc: "An analytics dashboard visualizing large datasets with D3.js.",
    icon: null,
    image: null,
    video: null,
    logo: null,
  },
  {
    name: "CLI Toolkit",
    url: null,
    tag: "Node / CLI",
    subject: "Developer Tools",
    branch: "Automation",
    date: "—",
    status: "—",
    shortDesc: "Placeholder description.",
    desc: "A command-line developer toolkit with scaffolding and build automation.",
    icon: null,
    image: null,
    video: null,
    logo: null,
  },
  {
    name: "Mobile App",
    url: null,
    tag: "React Native",
    subject: "Mobile Development",
    branch: "Cross-Platform",
    date: "—",
    status: "—",
    shortDesc: "Placeholder description.",
    desc: "A cross-platform mobile app for tracking study sessions and goals.",
    icon: null,
    image: null,
    video: null,
    logo: null,
  },
];
