export const PROJECTS = [
  {
    name: "ColorWaste",
    url: "https://colorwaste.com",
    tag: "C++ / JS / PHP / MySQL ",
    subject: "Machine Learning",
    branch: "Computer Vision",
    date: "February 2026",
    status: "Completed",
    shortDesc:
      "ColorWaste is a waste segregation system using computer vision and sensors to automatically classify waste. It provides real-time feedback through a dashboard",
    icon: "/ColorWaste.png",
    image: null,
    video: "/Dashboard - Demo Vid.mp4",
    videoLabel: "Dashboard Demo",
    video2: "/Prototype - Demo Vid.mp4",
    video2Label: "Prototype Demo",
    iconLabel: "ColorWaste Website",
    logo: "/ColorWaste.png",
  },
  {
    name: "Portfolio",
    url: null,
    tag: "React / Three.js",
    subject: "Web Development",
    branch: "Front-End",
    date: "March 2026",
    status: "In-Progress",
    shortDesc:
      "My personal portfolio, showcasing my skills, projects, and experience as a Computer Science student.",
    icon: null,
    image: null,
    video: null,
    logo: null,
  },
  {
    name: "Album",
    url: null,
    tag: "HTML / CSS",
    subject: "Web Development",
    branch: "Front-End",
    date: "February 2026",
    status: "Completed",
    shortDesc:
      "Album website I made to view personal images and personalized letters.",
    icon: null,
    image: null,
    video: null,
    logo: null,
  },
  {
    name: "Img to ASCII",
    url: null,
    tag: "React / Canvas API",
    subject: "Image Processing",
    branch: "Creative Coding",
    date: "April 2026",
    status: "Work in Progress",
    shortDesc:
      "A drawing application built with React and Canvas API that converts drawings and uploaded images into ASCII art. Features adjustable brush, eraser tool, image upload, and real-time canvas manipulation.",
    icon: null,
    image: null,
    video: null,
    logo: null,
  },
  {
    name: "DICT-TMS",
    url: null,
    tag: "React / Tailwind CSS / JS / PostgreSQL",
    subject: "Web Development",
    branch: "Information Systems",
    date: "April 2026",
    status: "Work in Progress",
    shortDesc:
      "DICT-TMS is a full-featured learning management system where users can enroll in and complete courses, while staff members have administrative privileges to upload, organize, and manage course content efficiently.",
    icon: null,
    image: null,
    video: null,
    logo: null,
  },
  {
    name: "Stitched",
    url: null,
    tag: "React / JS / Canvas",
    subject: "Creative Tools / Simulation",
    branch: "Information Systems",
    date: "April 2026",
    status: "Work in Progress",
    shortDesc:
      "Stitched is an interactive embroidery simulator built on Canvas and React. Users stitch patterns onto a woven cloth by clicking and dragging a needle cursor that mirror real hand embroidery.",
    icon: null,
    image: null,
    video: null,
    logo: null,
  },
];
